'use client'

import { useState, useMemo, useRef } from 'react'
import { addGroupMember, removeGroupMember, subscribeToGroup, updateGroupName } from '../../lib/firestore'
import { useEffect } from 'react'

export default function GroupInfoModal({ 
  groupId, 
  group: initialGroup, 
  user, 
  allUsers, 
  onClose
}) {
  const [group, setGroup] = useState(initialGroup)
  const [showAddMember, setShowAddMember] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [adding, setAdding] = useState(false)
  const [removing, setRemoving] = useState(null)
  const [editingName, setEditingName] = useState(false)
  const [newName, setNewName] = useState('')
  const [savingName, setSavingName] = useState(false)
  const searchInputRef = useRef(null)
  const nameInputRef = useRef(null)

  // Subscribe to group updates
  useEffect(() => {
    if (!groupId) return
    
    const unsubscribe = subscribeToGroup(groupId, updatedGroup => {
      if (updatedGroup) {
        setGroup(updatedGroup)
      }
    })

    return () => unsubscribe()
  }, [groupId])

  // Get members from the group
  const members = useMemo(() => {
    if (!group?.members) return []
    
    return Object.entries(group.members).map(([uid, memberData]) => {
      // Try to find full user data from allUsers
      const fullUser = allUsers.find(u => u.uid === uid)
      return {
        uid,
        displayName: fullUser?.displayName || memberData.displayName || memberData.email?.split('@')[0] || 'Unknown',
        email: fullUser?.email || memberData.email || '',
        photoURL: fullUser?.photoURL || memberData.photoURL || '',
        joinedAt: memberData.joinedAt,
      }
    })
  }, [group, allUsers])

  // Users not in the group (for add member)
  const availableUsers = useMemo(() => {
    if (!group?.members) return allUsers.filter(u => u.uid !== user?.uid)
    const memberIds = Object.keys(group.members)
    return allUsers.filter(u => !memberIds.includes(u.uid))
  }, [allUsers, group, user])

  // Filtered users for search
  const filteredAvailableUsers = useMemo(() => {
    if (!searchQuery.trim()) return availableUsers
    const query = searchQuery.toLowerCase()
    return availableUsers.filter(u => 
      u.displayName?.toLowerCase().includes(query) ||
      u.email?.toLowerCase().includes(query)
    )
  }, [availableUsers, searchQuery])

  // Focus search input when add member form appears
  useEffect(() => {
    if (showAddMember && searchInputRef.current) {
      searchInputRef.current.focus()
    }
  }, [showAddMember])

  // Focus name input when editing
  useEffect(() => {
    if (editingName && nameInputRef.current) {
      nameInputRef.current.focus()
      nameInputRef.current.select()
    }
  }, [editingName])

  // Generate display name (auto-generated from member names if no custom name)
  const autoGeneratedName = members.map(m => m.displayName?.split(' ')[0] || m.email?.split('@')[0]).join(', ')
  const groupDisplayName = group?.name || group?.displayName || autoGeneratedName
  const hasCustomName = !!group?.name

  // Start editing name
  const handleStartEditName = () => {
    setNewName(group?.name || '')
    setEditingName(true)
  }

  // Save new name
  const handleSaveName = async () => {
    if (savingName) return
    
    const trimmedName = newName.trim()
    
    // If empty, we'll clear the custom name (revert to auto-generated)
    setSavingName(true)
    
    try {
      await updateGroupName(groupId, trimmedName || null)
      setEditingName(false)
    } catch (error) {
      console.error('Error updating group name:', error)
      alert('Failed to update group name. Please try again.')
    } finally {
      setSavingName(false)
    }
  }

  // Cancel editing
  const handleCancelEdit = () => {
    setEditingName(false)
    setNewName('')
  }

  // Handle enter key in name input
  const handleNameKeyDown = (e) => {
    if (e.key === 'Enter') {
      handleSaveName()
    } else if (e.key === 'Escape') {
      handleCancelEdit()
    }
  }

  const handleAddMember = async (memberToAdd) => {
    if (adding) return
    setAdding(true)
    
    try {
      await addGroupMember(groupId, memberToAdd)
      setSearchQuery('')
    } catch (error) {
      console.error('Error adding member:', error)
      alert('Failed to add member. Please try again.')
    } finally {
      setAdding(false)
    }
  }

  const handleRemoveMember = async (memberUid) => {
    if (removing) return
    
    // Confirm removal
    if (!confirm('Remove this member from the group?')) return
    
    setRemoving(memberUid)
    
    try {
      await removeGroupMember(groupId, memberUid)
    } catch (error) {
      console.error('Error removing member:', error)
      alert('Failed to remove member. Please try again.')
    } finally {
      setRemoving(null)
    }
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content group-info-modal" onClick={e => e.stopPropagation()}>
        {/* Header with close button */}
        <button className="modal-close-btn-top" onClick={onClose}>✕</button>

        {/* Stacked avatars */}
        <div className="group-info-avatars">
          {members.slice(0, 4).map((member, idx) => (
            member.photoURL ? (
              <img 
                key={member.uid}
                src={member.photoURL} 
                alt={member.displayName} 
                className='group-info-avatar'
                style={{ 
                  zIndex: 4 - idx,
                  marginLeft: idx > 0 ? '-12px' : '0'
                }}
              />
            ) : (
              <div 
                key={member.uid}
                className='group-info-avatar-fallback'
                style={{ 
                  zIndex: 4 - idx,
                  marginLeft: idx > 0 ? '-12px' : '0'
                }}
              >
                {(member.displayName || '?')[0].toUpperCase()}
              </div>
            )
          ))}
        </div>

        {/* Group name - editable */}
        {editingName ? (
          <div className="group-name-edit">
            <input
              ref={nameInputRef}
              type="text"
              value={newName}
              onChange={e => setNewName(e.target.value)}
              onKeyDown={handleNameKeyDown}
              placeholder="Enter group name..."
              className="group-name-input"
              maxLength={50}
            />
            <div className="group-name-actions">
              <button 
                className="name-save-btn" 
                onClick={handleSaveName}
                disabled={savingName}
              >
                {savingName ? '...' : 'Save'}
              </button>
              <button 
                className="name-cancel-btn" 
                onClick={handleCancelEdit}
              >
                Cancel
              </button>
            </div>
            <p className="group-name-hint">
              Leave empty to use auto-generated name
            </p>
          </div>
        ) : (
          <div className="group-name-display" onClick={handleStartEditName}>
            <h2 className="group-info-name">{groupDisplayName}</h2>
            <span className="edit-name-icon">✏️</span>
            {!hasCustomName && (
              <p className="group-name-auto">Tap to set a custom name</p>
            )}
          </div>
        )}

        {/* Member list */}
        <div className="group-info-section">
          <div className="group-info-section-header">
            <span>Members ({members.length})</span>
            {!showAddMember && (
              <button 
                className="group-info-add-member-btn"
                onClick={() => setShowAddMember(true)}
              >
                ＋ Add
              </button>
            )}
          </div>

          {/* Add member form - shows at top when active */}
          {showAddMember && (
            <div 
              className="add-member-form"
              onMouseDown={e => e.stopPropagation()}
              onClick={e => e.stopPropagation()}
            >
              <input
                ref={searchInputRef}
                type="text"
                placeholder="Search team members..."
                value={searchQuery}
                onChange={e => setSearchQuery(e.target.value)}
                className="add-member-search"
                autoFocus
                onMouseDown={e => e.stopPropagation()}
                onFocus={e => e.stopPropagation()}
              />
              <div className="add-member-list">
                {filteredAvailableUsers.map(u => (
                  <div 
                    key={u.uid} 
                    className="add-member-item"
                    onClick={() => handleAddMember(u)}
                  >
                    <div className="add-member-avatar">
                      {u.photoURL ? (
                        <img src={u.photoURL} alt={u.displayName} />
                      ) : (
                        <div className="avatar-fallback">
                          {(u.displayName || u.email || '?')[0].toUpperCase()}
                        </div>
                      )}
                    </div>
                    <span>{u.displayName || u.email}</span>
                    <span className="add-btn">{adding ? '...' : 'Add'}</span>
                  </div>
                ))}
                {filteredAvailableUsers.length === 0 && (
                  <div className="no-users-found">No team members to add</div>
                )}
              </div>
              <button 
                className="cancel-add-btn"
                onClick={() => {
                  setShowAddMember(false)
                  setSearchQuery('')
                }}
              >
                Cancel
              </button>
            </div>
          )}
          
          <div className="group-info-members">
            {members.map(member => (
              <div key={member.uid} className="group-info-member">
                <div className="group-info-member-avatar">
                  {member.photoURL ? (
                    <img src={member.photoURL} alt={member.displayName} />
                  ) : (
                    <div className="avatar-fallback">
                      {(member.displayName || '?')[0].toUpperCase()}
                    </div>
                  )}
                </div>
                <div className="group-info-member-info">
                  <span className="group-info-member-name">
                    {member.displayName}
                    {member.uid === user?.uid && <span className="you-badge"> (You)</span>}
                  </span>
                </div>
                {member.uid !== user?.uid && (
                  <button 
                    className="group-info-member-remove"
                    onClick={() => handleRemoveMember(member.uid)}
                    disabled={removing === member.uid}
                  >
                    {removing === member.uid ? '...' : '✕'}
                  </button>
                )}
              </div>
            ))}
          </div>
        </div>

        <style jsx>{`
          .group-info-modal {
            max-width: 280px;
            padding: 16px;
            text-align: center;
          }

          .modal-close-btn-top {
            position: absolute;
            top: 12px;
            right: 12px;
            background: none;
            border: none;
            font-size: 20px;
            cursor: pointer;
            color: var(--color-text-secondary);
            padding: 4px 8px;
            border-radius: 6px;
            transition: background 0.2s;
          }

          .modal-close-btn-top:hover {
            background: var(--color-hover);
          }

          .group-info-avatars {
            display: flex;
            justify-content: center;
            margin-bottom: 8px;
          }

          .group-info-avatar {
            width: 44px;
            height: 44px;
            border-radius: 50%;
            object-fit: cover;
            border: 2px solid var(--color-background);
          }

          .group-info-avatar-fallback {
            width: 44px;
            height: 44px;
            border-radius: 50%;
            background: linear-gradient(135deg, #8e8e93 0%, #636366 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 16px;
            font-weight: 600;
            color: white;
            border: 2px solid var(--color-background);
          }

          .group-info-name {
            font-size: 14px;
            font-weight: 600;
            margin: 0;
            color: var(--color-text);
          }

          .group-name-display {
            cursor: pointer;
            padding: 8px 12px;
            margin: 0 0 16px 0;
            border-radius: 10px;
            transition: background 0.2s;
            position: relative;
          }

          .group-name-display:hover {
            background: var(--color-hover);
          }

          .group-name-display:hover .edit-name-icon {
            opacity: 1;
          }

          .edit-name-icon {
            position: absolute;
            right: 8px;
            top: 50%;
            transform: translateY(-50%);
            font-size: 14px;
            opacity: 0.4;
            transition: opacity 0.2s;
          }

          .group-name-auto {
            font-size: 12px;
            color: var(--color-text-secondary);
            margin: 4px 0 0 0;
          }

          .group-name-edit {
            margin-bottom: 16px;
          }

          .group-name-input {
            width: 100%;
            padding: 10px 14px;
            border-radius: 10px;
            border: 1px solid var(--color-primary);
            background: var(--color-input-bg);
            color: var(--color-text);
            font-size: 16px;
            font-weight: 500;
            text-align: center;
            outline: none;
          }

          .group-name-actions {
            display: flex;
            gap: 8px;
            justify-content: center;
            margin-top: 10px;
          }

          .name-save-btn {
            padding: 8px 20px;
            border-radius: 8px;
            border: none;
            background: linear-gradient(135deg, #34C759 0%, #248A3D 100%);
            color: #fff;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s;
            box-shadow: 0 2px 8px rgba(52, 199, 89, 0.3);
          }

          .name-save-btn:hover:not(:disabled) {
            transform: translateY(-1px);
            box-shadow: 0 4px 12px rgba(52, 199, 89, 0.4);
          }

          .name-save-btn:disabled {
            opacity: 0.5;
            transform: none;
            box-shadow: none;
          }

          .name-cancel-btn {
            padding: 6px 16px;
            border-radius: 8px;
            border: 1px solid var(--color-border);
            background: none;
            color: var(--color-text-secondary);
            font-size: 13px;
            cursor: pointer;
            transition: background 0.2s;
          }

          .name-cancel-btn:hover {
            background: var(--color-hover);
          }

          .group-name-hint {
            font-size: 11px;
            color: var(--color-text-secondary);
            margin: 8px 0 0 0;
            opacity: 0.7;
          }

          .group-info-section {
            text-align: left;
            margin-top: 12px;
          }

          .group-info-section-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-size: 10px;
            font-weight: 600;
            color: var(--color-text-secondary);
            text-transform: uppercase;
            margin-bottom: 6px;
            letter-spacing: 0.5px;
          }

          .group-info-add-member-btn {
            background: none;
            border: none;
            color: var(--color-primary);
            font-size: 11px;
            font-weight: 600;
            cursor: pointer;
            padding: 2px 6px;
            border-radius: 4px;
            text-transform: none;
            transition: background 0.15s;
          }

          .group-info-add-member-btn:hover {
            background: rgba(52, 199, 89, 0.1);
          }

          .group-info-members {
            background: var(--color-hover);
            border-radius: 8px;
            overflow: hidden;
            max-height: 180px;
            overflow-y: auto;
          }

          .group-info-member {
            display: flex;
            align-items: center;
            gap: 8px;
            padding: 6px 10px;
            border-bottom: 1px solid var(--color-border);
            position: relative;
          }

          .group-info-member:last-child {
            border-bottom: none;
          }

          .group-info-member:hover .group-info-member-remove {
            opacity: 1;
          }

          .group-info-member-avatar img,
          .group-info-member-avatar .avatar-fallback {
            width: 28px;
            height: 28px;
            border-radius: 50%;
            object-fit: cover;
          }

          .group-info-member-avatar .avatar-fallback {
            background: linear-gradient(135deg, #8e8e93 0%, #636366 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 11px;
            font-weight: 600;
            color: white;
          }

          .group-info-member-info {
            flex: 1;
            min-width: 0;
          }

          .group-info-member-name {
            display: block;
            font-weight: 500;
            font-size: 13px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
          }

          .you-badge {
            font-weight: 400;
            font-size: 11px;
            color: var(--color-text-secondary);
          }

          .group-info-member-remove {
            background: none;
            border: none;
            color: #ff3b30;
            font-size: 12px;
            cursor: pointer;
            padding: 2px 6px;
            border-radius: 4px;
            opacity: 0;
            transition: opacity 0.15s;
          }

          .group-info-member-remove:hover {
            opacity: 1;
            background: rgba(255, 59, 48, 0.1);
          }

          .group-info-add-member {
            display: flex;
            align-items: center;
            gap: 10px;
            width: 100%;
            padding: 12px;
            background: none;
            border: none;
            cursor: pointer;
            color: var(--color-primary);
            font-size: 14px;
            font-weight: 500;
            transition: background 0.2s;
          }

          .group-info-add-member:hover {
            background: rgba(52, 199, 89, 0.1);
          }

          .add-icon {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            background: linear-gradient(135deg, #34C759 0%, #30B350 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 20px;
            color: white;
          }

          .add-member-form {
            padding: 12px;
          }

          .add-member-search {
            width: 100%;
            padding: 10px 12px;
            border-radius: 8px;
            border: 1px solid var(--color-border);
            background: var(--color-input-bg);
            color: var(--color-text);
            font-size: 14px;
            margin-bottom: 8px;
          }

          .add-member-list {
            max-height: 200px;
            overflow-y: auto;
          }

          .add-member-item {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 8px;
            border-radius: 6px;
            cursor: pointer;
            transition: background 0.15s;
          }

          .add-member-item:hover {
            background: var(--color-background);
          }

          .add-member-avatar img,
          .add-member-avatar .avatar-fallback {
            width: 32px;
            height: 32px;
            border-radius: 50%;
            object-fit: cover;
          }

          .add-member-avatar .avatar-fallback {
            background: linear-gradient(135deg, #8e8e93 0%, #636366 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 12px;
            font-weight: 600;
            color: white;
          }

          .add-member-item span:nth-child(2) {
            flex: 1;
            font-size: 14px;
          }

          .add-btn {
            color: var(--color-primary);
            font-size: 13px;
            font-weight: 500;
          }

          .no-users-found {
            padding: 16px;
            text-align: center;
            color: var(--color-text-secondary);
            font-size: 13px;
          }

          .cancel-add-btn {
            width: 100%;
            margin-top: 8px;
            padding: 8px;
            background: none;
            border: 1px solid var(--color-border);
            border-radius: 6px;
            color: var(--color-text-secondary);
            font-size: 13px;
            cursor: pointer;
            transition: background 0.2s;
          }

          .cancel-add-btn:hover {
            background: var(--color-hover);
          }
        `}</style>
      </div>
    </div>
  )
}

