'use client'

import { useState, useMemo, useRef, useCallback } from 'react'
import { useDropzone } from 'react-dropzone'
import { addGroupMember, removeGroupMember, subscribeToGroup, updateGroupName, updateGroupPhoto } from '../../lib/firestore'
import { useEffect } from 'react'

// Common emojis for group icons
const GROUP_EMOJIS = [
  '👥', '💼', '🚀', '💡', '🎯', '⭐', '🔥', '💪',
  '🎨', '🎬', '📱', '💻', '🎮', '🎵', '📚', '✨',
  '🌟', '💎', '🏆', '🎪', '🌈', '🦄', '🐱', '🐶',
  '🍕', '☕', '🍺', '🎂', '❤️', '💜', '💙', '💚',
]

export default function GroupInfoModal({ 
  groupId, 
  group: initialGroup, 
  user, 
  allUsers, 
  onClose
}) {
  const [group, setGroup] = useState(initialGroup)
  const [showAddMember, setShowAddMember] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [adding, setAdding] = useState(false)
  const [removing, setRemoving] = useState(null)
  const [editingName, setEditingName] = useState(false)
  const [newName, setNewName] = useState('')
  const [savingName, setSavingName] = useState(false)
  const [showPhotoPicker, setShowPhotoPicker] = useState(false)
  const [savingPhoto, setSavingPhoto] = useState(false)
  const searchInputRef = useRef(null)
  const nameInputRef = useRef(null)
  const fileInputRef = useRef(null)

  // Subscribe to group updates
  useEffect(() => {
    if (!groupId) return
    
    const unsubscribe = subscribeToGroup(groupId, updatedGroup => {
      if (updatedGroup) {
        setGroup(updatedGroup)
      }
    })

    return () => unsubscribe()
  }, [groupId])

  // Get members from the group
  const members = useMemo(() => {
    if (!group?.members) return []
    
    return Object.entries(group.members).map(([uid, memberData]) => {
      // Try to find full user data from allUsers
      const fullUser = allUsers.find(u => u.uid === uid)
      return {
        uid,
        displayName: fullUser?.displayName || memberData.displayName || memberData.email?.split('@')[0] || 'Unknown',
        email: fullUser?.email || memberData.email || '',
        photoURL: fullUser?.photoURL || memberData.photoURL || '',
        joinedAt: memberData.joinedAt,
      }
    })
  }, [group, allUsers])

  // Users not in the group (for add member)
  const availableUsers = useMemo(() => {
    if (!group?.members) return allUsers.filter(u => u.uid !== user?.uid)
    const memberIds = Object.keys(group.members)
    return allUsers.filter(u => !memberIds.includes(u.uid))
  }, [allUsers, group, user])

  // Filtered users for search
  const filteredAvailableUsers = useMemo(() => {
    if (!searchQuery.trim()) return availableUsers
    const query = searchQuery.toLowerCase()
    return availableUsers.filter(u => 
      u.displayName?.toLowerCase().includes(query) ||
      u.email?.toLowerCase().includes(query)
    )
  }, [availableUsers, searchQuery])

  // Focus search input when add member form appears
  useEffect(() => {
    if (showAddMember && searchInputRef.current) {
      searchInputRef.current.focus()
    }
  }, [showAddMember])

  // Focus name input when editing
  useEffect(() => {
    if (editingName && nameInputRef.current) {
      nameInputRef.current.focus()
      nameInputRef.current.select()
    }
  }, [editingName])

  // Generate display name (auto-generated from member names if no custom name)
  const autoGeneratedName = members.map(m => m.displayName?.split(' ')[0] || m.email?.split('@')[0]).join(', ')
  const groupDisplayName = group?.name || group?.displayName || autoGeneratedName
  const hasCustomName = !!group?.name

  // Start editing name
  const handleStartEditName = () => {
    setNewName(group?.name || '')
    setEditingName(true)
  }

  // Save new name
  const handleSaveName = async () => {
    if (savingName) return
    
    const trimmedName = newName.trim()
    
    // If empty, we'll clear the custom name (revert to auto-generated)
    setSavingName(true)
    
    try {
      await updateGroupName(groupId, trimmedName || null)
      setEditingName(false)
    } catch (error) {
      console.error('Error updating group name:', error)
      alert('Failed to update group name. Please try again.')
    } finally {
      setSavingName(false)
    }
  }

  // Cancel editing
  const handleCancelEdit = () => {
    setEditingName(false)
    setNewName('')
  }

  // Handle enter key in name input
  const handleNameKeyDown = (e) => {
    const isComposing = e.nativeEvent?.isComposing || e.isComposing
    if (e.key === 'Enter' && !isComposing) {
      handleSaveName()
    } else if (e.key === 'Escape') {
      handleCancelEdit()
    }
  }

  const handleAddMember = async (memberToAdd) => {
    if (adding) return
    setAdding(true)
    
    try {
      await addGroupMember(groupId, memberToAdd)
      setSearchQuery('')
    } catch (error) {
      console.error('Error adding member:', error)
      alert('Failed to add member. Please try again.')
    } finally {
      setAdding(false)
    }
  }

  const handleRemoveMember = async (memberUid) => {
    if (removing) return
    
    // Confirm removal
    if (!confirm('Remove this member from the group?')) return
    
    setRemoving(memberUid)
    
    try {
      await removeGroupMember(groupId, memberUid)
    } catch (error) {
      console.error('Error removing member:', error)
      alert('Failed to remove member. Please try again.')
    } finally {
      setRemoving(null)
    }
  }

  // Handle emoji selection for group photo
  const handleEmojiSelect = async (emoji) => {
    if (savingPhoto) return
    setSavingPhoto(true)
    
    try {
      await updateGroupPhoto(groupId, emoji)
      setShowPhotoPicker(false)
    } catch (error) {
      console.error('Error setting group emoji:', error)
      alert('Failed to update group photo. Please try again.')
    } finally {
      setSavingPhoto(false)
    }
  }

  // Handle file upload for group photo (used by both file input and drag-drop)
  const uploadPhotoFile = useCallback(async (file) => {
    if (!file || savingPhoto) return
    
    // Validate file type
    if (!file.type.startsWith('image/')) {
      alert('Please select an image file.')
      return
    }
    
    // Validate file size (max 5MB)
    if (file.size > 5 * 1024 * 1024) {
      alert('Image must be less than 5MB.')
      return
    }
    
    setSavingPhoto(true)
    
    try {
      // Upload to our API
      const formData = new FormData()
      formData.append('file', file)
      formData.append('groupId', groupId)
      
      const res = await fetch('/api/upload/group-photo', {
        method: 'POST',
        body: formData,
      })
      
      if (!res.ok) throw new Error('Upload failed')
      
      const { url } = await res.json()
      await updateGroupPhoto(groupId, url)
      setShowPhotoPicker(false)
    } catch (error) {
      console.error('Error uploading group photo:', error)
      alert('Failed to upload photo. Please try again.')
    } finally {
      setSavingPhoto(false)
    }
  }, [savingPhoto, groupId])

  // Handle file input change
  const handlePhotoUpload = async (e) => {
    const file = e.target.files?.[0]
    if (file) {
      await uploadPhotoFile(file)
    }
  }

  // Drag and drop handler
  const onDrop = useCallback((acceptedFiles) => {
    const file = acceptedFiles[0]
    if (file) {
      uploadPhotoFile(file)
    }
  }, [uploadPhotoFile])

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      'image/*': ['.png', '.jpg', '.jpeg', '.gif', '.webp']
    },
    multiple: false,
    noClick: true, // We'll handle click separately on the avatar
    noKeyboard: true
  })

  // Remove custom photo
  const handleRemovePhoto = async () => {
    if (savingPhoto) return
    setSavingPhoto(true)
    
    try {
      await updateGroupPhoto(groupId, null)
      setShowPhotoPicker(false)
    } catch (error) {
      console.error('Error removing group photo:', error)
    } finally {
      setSavingPhoto(false)
    }
  }

  // Combine dropzone props with our own click handler to prevent modal close
  const dropzoneRootProps = getRootProps({
    onClick: e => e.stopPropagation()
  })

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div 
        className="modal-content group-info-modal" 
        {...dropzoneRootProps}
      >
        <input {...getInputProps()} />
        
        {/* Drag overlay */}
        {isDragActive && (
          <div className="drop-overlay">
            <div className="drop-overlay-content">
              📷 Drop photo here
            </div>
          </div>
        )}
        
        {/* Header with close button */}
        <button className="modal-close-btn-top" onClick={onClose}>✕</button>

        {/* Group avatar - clickable to change */}
        <div 
          className="group-info-avatars clickable"
          onClick={() => setShowPhotoPicker(!showPhotoPicker)}
          title="Click to change group photo"
        >
          {group?.photoURL ? (
            // Custom photo (URL or emoji)
            group.photoURL.length <= 4 ? (
              // Emoji
              <div className="group-info-avatar-emoji">
                {group.photoURL}
              </div>
            ) : (
              // Image URL
              <img 
                src={group.photoURL} 
                alt="Group" 
                className='group-info-avatar-single'
              />
            )
          ) : (
            // Stacked avatars (default)
            members.slice(0, 4).map((member, idx) => (
              member.photoURL ? (
                <img 
                  key={member.uid}
                  src={member.photoURL} 
                  alt={member.displayName} 
                  className='group-info-avatar'
                  style={{ 
                    zIndex: 4 - idx,
                    marginLeft: idx > 0 ? '-12px' : '0'
                  }}
                />
              ) : (
                <div 
                  key={member.uid}
                  className='group-info-avatar-fallback'
                  style={{ 
                    zIndex: 4 - idx,
                    marginLeft: idx > 0 ? '-12px' : '0'
                  }}
                >
                  {(member.displayName || '?')[0].toUpperCase()}
                </div>
              )
            ))
          )}
          <div className="avatar-edit-hint">📷</div>
        </div>

        {/* Photo picker */}
        {showPhotoPicker && (
          <div className="photo-picker">
            <div className="photo-picker-header">
              <span>Choose group icon</span>
              <button className="photo-picker-close" onClick={() => setShowPhotoPicker(false)}>✕</button>
            </div>
            
            {/* Emoji grid */}
            <div className="emoji-grid">
              {GROUP_EMOJIS.map(emoji => (
                <button 
                  key={emoji} 
                  className="emoji-btn"
                  onClick={() => handleEmojiSelect(emoji)}
                  disabled={savingPhoto}
                >
                  {emoji}
                </button>
              ))}
            </div>
            
            {/* Upload button */}
            <div className="photo-picker-actions">
              <input 
                type="file" 
                ref={fileInputRef}
                accept="image/*"
                onChange={handlePhotoUpload}
                style={{ display: 'none' }}
              />
              <button 
                className="upload-photo-btn"
                onClick={() => fileInputRef.current?.click()}
                disabled={savingPhoto}
              >
                📤 Upload Photo
              </button>
              {group?.photoURL && (
                <button 
                  className="remove-photo-btn"
                  onClick={handleRemovePhoto}
                  disabled={savingPhoto}
                >
                  Remove
                </button>
              )}
            </div>
          </div>
        )}

        {/* Group name - editable */}
        {editingName ? (
          <div className="group-name-edit">
            <input
              ref={nameInputRef}
              type="text"
              value={newName}
              onChange={e => setNewName(e.target.value)}
              onKeyDown={handleNameKeyDown}
              placeholder="Enter group name..."
              className="group-name-input"
              maxLength={50}
            />
            <div className="group-name-actions">
              <button 
                className="name-save-btn" 
                onClick={handleSaveName}
                disabled={savingName}
              >
                {savingName ? '...' : 'Save'}
              </button>
              <button 
                className="name-cancel-btn" 
                onClick={handleCancelEdit}
              >
                Cancel
              </button>
            </div>
            <p className="group-name-hint">
              Leave empty to use auto-generated name
            </p>
          </div>
        ) : (
          <div className="group-name-display" onClick={handleStartEditName}>
            <h2 className="group-info-name">{groupDisplayName}</h2>
            <span className="edit-name-icon">✏️</span>
            {!hasCustomName && (
              <p className="group-name-auto">Tap to set a custom name</p>
            )}
          </div>
        )}

        {/* Member list */}
        <div className="group-info-section">
          <div className="group-info-section-header">
            <span>Members ({members.length})</span>
          </div>
          
          <div className="group-info-members">
            {/* Add New Member button - green plus icon */}
            {!showAddMember ? (
              <button 
                className="group-info-add-member"
                onClick={() => setShowAddMember(true)}
              >
                <span className="add-icon">＋</span>
                <span>Add New Member</span>
              </button>
            ) : (
              <div 
                className="add-member-form"
                onMouseDown={e => e.stopPropagation()}
                onClick={e => e.stopPropagation()}
              >
                <input
                  ref={searchInputRef}
                  type="text"
                  placeholder="Search team members..."
                  value={searchQuery}
                  onChange={e => setSearchQuery(e.target.value)}
                  className="add-member-search"
                  autoFocus
                  onMouseDown={e => e.stopPropagation()}
                  onFocus={e => e.stopPropagation()}
                />
                <div className="add-member-list">
                  {filteredAvailableUsers.map(u => (
                    <div 
                      key={u.uid} 
                      className="add-member-item"
                      onClick={() => handleAddMember(u)}
                    >
                      <div className="add-member-avatar">
                        {u.photoURL ? (
                          <img src={u.photoURL} alt={u.displayName} />
                        ) : (
                          <div className="avatar-fallback">
                            {(u.displayName || u.email || '?')[0].toUpperCase()}
                          </div>
                        )}
                      </div>
                      <span>{u.displayName || u.email}</span>
                      <span className="add-btn">{adding ? '...' : 'Add'}</span>
                    </div>
                  ))}
                  {filteredAvailableUsers.length === 0 && (
                    <div className="no-users-found">No team members to add</div>
                  )}
                </div>
                <button 
                  className="cancel-add-btn"
                  onClick={() => {
                    setShowAddMember(false)
                    setSearchQuery('')
                  }}
                >
                  Cancel
                </button>
              </div>
            )}
            {members.map(member => (
              <div key={member.uid} className="group-info-member">
                <div className="group-info-member-avatar">
                  {member.photoURL ? (
                    <img src={member.photoURL} alt={member.displayName} />
                  ) : (
                    <div className="avatar-fallback">
                      {(member.displayName || '?')[0].toUpperCase()}
                    </div>
                  )}
                </div>
                <div className="group-info-member-info">
                  <span className="group-info-member-name">
                    {member.displayName}
                    {member.uid === user?.uid && <span className="you-badge"> (You)</span>}
                  </span>
                </div>
                {member.uid !== user?.uid && (
                  <button 
                    className="group-info-member-remove"
                    onClick={() => handleRemoveMember(member.uid)}
                    disabled={removing === member.uid}
                  >
                    {removing === member.uid ? '...' : '✕'}
                  </button>
                )}
              </div>
            ))}
          </div>
        </div>

        <style jsx>{`
          .group-info-modal {
            max-width: 340px;
            padding: 20px;
            text-align: center;
            position: relative;
          }

          .drop-overlay {
            position: absolute;
            inset: 0;
            background: rgba(52, 199, 89, 0.9);
            border-radius: 16px;
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 100;
            pointer-events: none;
          }

          .drop-overlay-content {
            font-size: 18px;
            font-weight: 600;
            color: white;
            text-align: center;
            padding: 20px;
          }

          .modal-close-btn-top {
            position: absolute;
            top: 12px;
            right: 12px;
            background: none;
            border: none;
            font-size: 20px;
            cursor: pointer;
            color: var(--color-text-secondary);
            padding: 4px 8px;
            border-radius: 6px;
            transition: background 0.2s;
          }

          .modal-close-btn-top:hover {
            background: var(--color-hover);
          }

          .group-info-avatars {
            display: flex;
            justify-content: center;
            margin-bottom: 8px;
          }

          .group-info-avatar {
            width: 44px;
            height: 44px;
            border-radius: 50%;
            object-fit: cover;
            border: 2px solid var(--color-background);
          }

          .group-info-avatar-fallback {
            width: 44px;
            height: 44px;
            border-radius: 50%;
            background: linear-gradient(135deg, #8e8e93 0%, #636366 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 16px;
            font-weight: 600;
            color: white;
            border: 2px solid var(--color-background);
          }

          .group-info-avatars.clickable {
            cursor: pointer;
            position: relative;
            transition: opacity 0.2s;
          }

          .group-info-avatars.clickable:hover {
            opacity: 0.8;
          }

          .group-info-avatars.clickable:hover .avatar-edit-hint {
            opacity: 1;
          }

          .avatar-edit-hint {
            position: absolute;
            bottom: -2px;
            right: -2px;
            width: 22px;
            height: 22px;
            background: var(--color-primary);
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 11px;
            opacity: 0.7;
            transition: opacity 0.2s;
            box-shadow: 0 2px 6px rgba(0,0,0,0.3);
          }

          .group-info-avatar-single {
            width: 64px;
            height: 64px;
            border-radius: 50%;
            object-fit: cover;
            box-shadow: 0 2px 10px rgba(0,0,0,0.2);
          }

          .group-info-avatar-emoji {
            width: 64px;
            height: 64px;
            border-radius: 50%;
            background: linear-gradient(135deg, #3a3a4a 0%, #2a2a3a 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 32px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.2);
          }

          .photo-picker {
            background: var(--color-hover);
            border-radius: 12px;
            padding: 12px;
            margin-bottom: 12px;
          }

          .photo-picker-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
            font-size: 12px;
            font-weight: 600;
            color: var(--color-text-secondary);
          }

          .photo-picker-close {
            background: none;
            border: none;
            color: var(--color-text-secondary);
            cursor: pointer;
            padding: 2px 6px;
            border-radius: 4px;
          }

          .photo-picker-close:hover {
            background: var(--color-border);
          }

          .emoji-grid {
            display: grid;
            grid-template-columns: repeat(8, 1fr);
            gap: 4px;
            margin-bottom: 10px;
          }

          .emoji-btn {
            width: 32px;
            height: 32px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 18px;
            background: none;
            border: none;
            border-radius: 6px;
            cursor: pointer;
            transition: background 0.15s;
          }

          .emoji-btn:hover:not(:disabled) {
            background: var(--color-border);
          }

          .emoji-btn:disabled {
            opacity: 0.5;
            cursor: not-allowed;
          }

          .photo-picker-actions {
            display: flex;
            gap: 8px;
            justify-content: center;
          }

          .upload-photo-btn {
            padding: 6px 12px;
            border-radius: 8px;
            border: none;
            background: var(--color-primary);
            color: white;
            font-size: 12px;
            font-weight: 500;
            cursor: pointer;
            transition: opacity 0.2s;
          }

          .upload-photo-btn:hover:not(:disabled) {
            opacity: 0.9;
          }

          .upload-photo-btn:disabled {
            opacity: 0.5;
            cursor: not-allowed;
          }

          .remove-photo-btn {
            padding: 6px 12px;
            border-radius: 8px;
            border: 1px solid var(--color-border);
            background: none;
            color: var(--color-text-secondary);
            font-size: 12px;
            cursor: pointer;
            transition: background 0.2s;
          }

          .remove-photo-btn:hover:not(:disabled) {
            background: var(--color-hover);
          }

          .group-info-name {
            font-size: 14px;
            font-weight: 600;
            margin: 0;
            color: var(--color-text);
          }

          .group-name-display {
            cursor: pointer;
            padding: 8px 12px;
            margin: 0 0 16px 0;
            border-radius: 10px;
            transition: background 0.2s;
            position: relative;
          }

          .group-name-display:hover {
            background: var(--color-hover);
          }

          .group-name-display:hover .edit-name-icon {
            opacity: 1;
          }

          .edit-name-icon {
            position: absolute;
            right: 8px;
            top: 50%;
            transform: translateY(-50%);
            font-size: 14px;
            opacity: 0.4;
            transition: opacity 0.2s;
          }

          .group-name-auto {
            font-size: 12px;
            color: var(--color-text-secondary);
            margin: 4px 0 0 0;
          }

          .group-name-edit {
            margin-bottom: 16px;
          }

          .group-name-input {
            width: 100%;
            padding: 10px 14px;
            border-radius: 10px;
            border: 1px solid var(--color-primary);
            background: var(--color-input-bg);
            color: var(--color-text);
            font-size: 16px;
            font-weight: 500;
            text-align: center;
            outline: none;
          }

          .group-name-actions {
            display: flex;
            gap: 8px;
            justify-content: center;
            margin-top: 10px;
          }

          .name-save-btn {
            padding: 8px 20px;
            border-radius: 8px;
            border: none;
            background: linear-gradient(135deg, #34C759 0%, #248A3D 100%);
            color: #fff;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s;
            box-shadow: 0 2px 8px rgba(52, 199, 89, 0.3);
          }

          .name-save-btn:hover:not(:disabled) {
            transform: translateY(-1px);
            box-shadow: 0 4px 12px rgba(52, 199, 89, 0.4);
          }

          .name-save-btn:disabled {
            opacity: 0.5;
            transform: none;
            box-shadow: none;
          }

          .name-cancel-btn {
            padding: 6px 16px;
            border-radius: 8px;
            border: 1px solid var(--color-border);
            background: none;
            color: var(--color-text-secondary);
            font-size: 13px;
            cursor: pointer;
            transition: background 0.2s;
          }

          .name-cancel-btn:hover {
            background: var(--color-hover);
          }

          .group-name-hint {
            font-size: 11px;
            color: var(--color-text-secondary);
            margin: 8px 0 0 0;
            opacity: 0.7;
          }

          .group-info-section {
            text-align: left;
            margin-top: 12px;
          }

          .group-info-section-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-size: 10px;
            font-weight: 600;
            color: var(--color-text-secondary);
            text-transform: uppercase;
            margin-bottom: 6px;
            letter-spacing: 0.5px;
          }

          .group-info-add-member-btn {
            background: none;
            border: none;
            color: var(--color-primary);
            font-size: 11px;
            font-weight: 600;
            cursor: pointer;
            padding: 2px 6px;
            border-radius: 4px;
            text-transform: none;
            transition: background 0.15s;
          }

          .group-info-add-member-btn:hover {
            background: rgba(52, 199, 89, 0.1);
          }

          .group-info-members {
            background: var(--color-hover);
            border-radius: 10px;
            overflow: hidden;
            max-height: 280px;
            overflow-y: auto;
          }

          .group-info-member {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 10px 12px;
            border-bottom: 1px solid var(--color-border);
            position: relative;
          }

          .group-info-member:last-child {
            border-bottom: none;
          }

          .group-info-member:hover .group-info-member-remove {
            opacity: 1;
          }

          .group-info-member-avatar img,
          .group-info-member-avatar .avatar-fallback {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            object-fit: cover;
          }

          .group-info-member-avatar .avatar-fallback {
            background: linear-gradient(135deg, #8e8e93 0%, #636366 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 14px;
            font-weight: 600;
            color: white;
          }

          .group-info-member-info {
            flex: 1;
            min-width: 0;
          }

          .group-info-member-name {
            display: block;
            font-weight: 500;
            font-size: 15px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
          }

          .you-badge {
            font-weight: 400;
            font-size: 11px;
            color: var(--color-text-secondary);
          }

          .group-info-member-remove {
            background: none;
            border: none;
            color: #ff3b30;
            font-size: 12px;
            cursor: pointer;
            padding: 2px 6px;
            border-radius: 4px;
            opacity: 0;
            transition: opacity 0.15s;
          }

          .group-info-member-remove:hover {
            opacity: 1;
            background: rgba(255, 59, 48, 0.1);
          }

          .group-info-add-member {
            display: flex;
            align-items: center;
            gap: 10px;
            width: 100%;
            padding: 12px;
            background: none;
            border: none;
            cursor: pointer;
            color: var(--color-primary);
            font-size: 14px;
            font-weight: 500;
            transition: background 0.2s;
          }

          .group-info-add-member:hover {
            background: rgba(52, 199, 89, 0.1);
          }

          .add-icon {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            background: linear-gradient(135deg, #34C759 0%, #30B350 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 20px;
            color: white;
          }

          .add-member-form {
            padding: 12px;
          }

          .add-member-search {
            width: 100%;
            padding: 10px 12px;
            border-radius: 8px;
            border: 1px solid var(--color-border);
            background: var(--color-input-bg);
            color: var(--color-text);
            font-size: 14px;
            margin-bottom: 8px;
          }

          .add-member-list {
            max-height: 200px;
            overflow-y: auto;
          }

          .add-member-item {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 8px;
            border-radius: 6px;
            cursor: pointer;
            transition: background 0.15s;
          }

          .add-member-item:hover {
            background: var(--color-background);
          }

          .add-member-avatar img,
          .add-member-avatar .avatar-fallback {
            width: 32px;
            height: 32px;
            border-radius: 50%;
            object-fit: cover;
          }

          .add-member-avatar .avatar-fallback {
            background: linear-gradient(135deg, #8e8e93 0%, #636366 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 12px;
            font-weight: 600;
            color: white;
          }

          .add-member-item span:nth-child(2) {
            flex: 1;
            font-size: 14px;
          }

          .add-btn {
            color: var(--color-primary);
            font-size: 13px;
            font-weight: 500;
          }

          .no-users-found {
            padding: 16px;
            text-align: center;
            color: var(--color-text-secondary);
            font-size: 13px;
          }

          .cancel-add-btn {
            width: 100%;
            margin-top: 8px;
            padding: 8px;
            background: none;
            border: 1px solid var(--color-border);
            border-radius: 6px;
            color: var(--color-text-secondary);
            font-size: 13px;
            cursor: pointer;
            transition: background 0.2s;
          }

          .cancel-add-btn:hover {
            background: var(--color-hover);
          }
        `}</style>
      </div>
    </div>
  )
}

